#!/usr/bin/env bun
// Generates the course's sentence audio with the same free Edge neural
// voices as scripts/generate-audio.mjs. Run with bun, which reads the
// TypeScript course data (and its "@/" imports) directly:
//
//   bun run generate-course-audio             generate only missing files
//   bun run generate-course-audio -- --force  regenerate every file
//
// Every sentence in src/data/course/ gets two clips, named after its id:
//   public/course/<unit>/audio/<sentenceId>.mp3       normal speed
//   public/course/<unit>/audio/<sentenceId>.slow.mp3  for "play slowly"
// read by the voice the sentence asks for ("f" by default). The manifest
// src/data/course-audio.generated.ts is rewritten on every run.

import { MsEdgeTTS, OUTPUT_FORMAT } from "msedge-tts";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { COURSE_UNITS } from "@/data/course";

const ROOT = path.dirname(import.meta.dir);
const MANIFEST_PATH = path.join(ROOT, "src", "data", "course-audio.generated.ts");

// Two voices so dialogues have two distinct speakers.
const VOICES = { f: "de-DE-KatjaNeural", m: "de-DE-ConradNeural" } as const;
const NORMAL_RATE = "-10%";
const SLOW_RATE = "-40%";

const force = process.argv.includes("--force");

async function synthesize(text: string, voice: string, rate: string): Promise<Buffer> {
  const tts = new MsEdgeTTS();
  await tts.setMetadata(voice, OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3);
  const { audioStream } = tts.toStream(text, { rate });
  const chunks: Buffer[] = [];
  for await (const chunk of audioStream) chunks.push(chunk as Buffer);
  return Buffer.concat(chunks);
}

async function writeIfMissing(filePath: string, text: string, voice: string, rate: string) {
  const label = path.relative(path.join(ROOT, "public"), filePath).replaceAll("\\", "/");
  if (existsSync(filePath) && !force) {
    console.log(`skip   ${label}`);
    return;
  }
  const buffer = await synthesize(text, voice, rate);
  if (buffer.length === 0) throw new Error(`empty audio for ${label}`);
  await writeFile(filePath, buffer);
  console.log(`wrote  ${label} (${buffer.length} bytes) — "${text}"`);
}

const entries: string[] = [];
for (const unit of COURSE_UNITS) {
  const dir = path.join(ROOT, "public", "course", unit.id, "audio");
  await mkdir(dir, { recursive: true });
  for (const lesson of unit.lessons) {
    for (const sentence of lesson.sentences) {
      const voice = VOICES[sentence.voice ?? "f"];
      const base = `/course/${unit.id}/audio/${sentence.id}`;
      await writeIfMissing(
        path.join(dir, `${sentence.id}.mp3`),
        sentence.german,
        voice,
        NORMAL_RATE,
      );
      await writeIfMissing(
        path.join(dir, `${sentence.id}.slow.mp3`),
        sentence.german,
        voice,
        SLOW_RATE,
      );
      entries.push(
        `  ${JSON.stringify(sentence.id)}: { src: "${base}.mp3", slow: "${base}.slow.mp3" },`,
      );
    }
  }
}

await writeFile(
  MANIFEST_PATH,
  `// AUTO-GENERATED by scripts/generate-course-audio.ts — do not edit by hand.
// Maps a course sentence id to its normal and slow audio clips.
export const COURSE_AUDIO: Record<string, { src: string; slow: string }> = {
${entries.join("\n")}
};
`,
);
console.log(`wrote  ${path.relative(ROOT, MANIFEST_PATH)}`);
