#!/usr/bin/env node
// Generates German pronunciation audio using Microsoft Edge's free neural
// TTS voices (via `msedge-tts` — the same voices behind Edge's "Read Aloud"
// feature, no API key or account needed).
//
// Usage:
//   bun run generate-audio             generate only missing files
//   bun run generate-audio -- --force  regenerate every file
//
// To add a new word or lesson-screen title: add an entry to WORDS or TITLES
// below, then rerun this script.
// It writes small mp3s under public/audio/ (or, for a word that belongs to
// one specific test, under that test's own `public/<n.n test name>/audio/`
// folder — see the `dir` field below and AGENTS.md's asset-layout
// convention) and regenerates the manifests at
// src/data/word-audio.generated.ts and src/data/letter-audio.generated.ts
// that the app imports at runtime.

import { MsEdgeTTS, OUTPUT_FORMAT } from "msedge-tts";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const AUDIO_DIR = path.join(ROOT, "public", "audio");
const LETTERS_DIR = path.join(AUDIO_DIR, "letters");
const WORD_MANIFEST_PATH = path.join(ROOT, "src", "data", "word-audio.generated.ts");
const LETTER_MANIFEST_PATH = path.join(ROOT, "src", "data", "letter-audio.generated.ts");

const VOICE = "de-DE-KatjaNeural"; // friendly female voice, good for kids

// word: what gets spoken (including the article, since kids need to learn it).
// slug: the mp3 filename, also used as the word's stable id.
// dir: output folder under public/, relative (default "audio"). Words that
// belong to one specific test's own vocabulary (not shared across tests,
// unlike letters/titles/articles) use their test's folder, e.g.
// "1.1 greetings/audio" — see AGENTS.md.
const WORDS = [
  { word: "der Hund", slug: "hund" },
  { word: "die Katze", slug: "katze" },
  { word: "der Vogel", slug: "vogel" },
  { word: "das Pferd", slug: "pferd" },
  { word: "das Buch", slug: "buch" },
  { word: "der", slug: "article-der" },
  { word: "die", slug: "article-die" },
  { word: "das", slug: "article-das" },
  { word: "Hallo", slug: "hallo", dir: "1.1 greetings/audio" },
  { word: "Guten Morgen", slug: "guten-morgen", dir: "1.1 greetings/audio" },
  { word: "Guten Tag", slug: "guten-tag", dir: "1.1 greetings/audio" },
  { word: "Guten Abend", slug: "guten-abend", dir: "1.1 greetings/audio" },
  { word: "Gute Nacht", slug: "gute-nacht", dir: "1.1 greetings/audio" },
  { word: "Tschüss", slug: "tschuess", dir: "1.1 greetings/audio" },
  { word: "Auf Wiedersehen", slug: "auf-wiedersehen", dir: "1.1 greetings/audio" },
  { word: "Bis bald", slug: "bis-bald", dir: "1.1 greetings/audio" },
  { word: "Wie geht's?", slug: "wie-gehts", dir: "1.1 greetings/audio" },
  { word: "Willkommen", slug: "willkommen", dir: "1.1 greetings/audio" },
  { word: "Bitte", slug: "bitte", dir: "1.1 greetings/audio" },
  { word: "Danke", slug: "danke", dir: "1.1 greetings/audio" },
  { word: "Vielen Dank", slug: "vielen-dank", dir: "1.1 greetings/audio" },
  { word: "Gern geschehen", slug: "gern-geschehen", dir: "1.1 greetings/audio" },
  { word: "Entschuldigung", slug: "entschuldigung", dir: "1.1 greetings/audio" },
  { word: "Sorry", slug: "sorry", dir: "1.1 greetings/audio" },
  { word: "Natürlich", slug: "natuerlich", dir: "1.1 greetings/audio" },
  { word: "Richtig", slug: "richtig", dir: "1.1 greetings/audio" },
  { word: "Kein Problem", slug: "kein-problem", dir: "1.1 greetings/audio" },
  { word: "Alles klar", slug: "alles-klar", dir: "1.1 greetings/audio" },
  { word: "Bis später", slug: "bis-spaeter", dir: "1.1 greetings/audio" },
  { word: "Bis morgen", slug: "bis-morgen", dir: "1.1 greetings/audio" },
  { word: "Viel Glück", slug: "viel-glueck", dir: "1.1 greetings/audio" },
  { word: "Gute Reise", slug: "gute-reise", dir: "1.1 greetings/audio" },
  { word: "die Familie", slug: "familie", dir: "1.2 family/audio" },
  { word: "die Eltern", slug: "eltern", dir: "1.2 family/audio" },
  { word: "der Vater", slug: "vater", dir: "1.2 family/audio" },
  { word: "die Mutter", slug: "mutter", dir: "1.2 family/audio" },
  { word: "der Sohn", slug: "sohn", dir: "1.2 family/audio" },
  { word: "die Tochter", slug: "tochter", dir: "1.2 family/audio" },
  { word: "der Bruder", slug: "bruder", dir: "1.2 family/audio" },
  { word: "die Schwester", slug: "schwester", dir: "1.2 family/audio" },
  { word: "der Großvater", slug: "grossvater", dir: "1.2 family/audio" },
  { word: "die Großmutter", slug: "grossmutter", dir: "1.2 family/audio" },
  { word: "die Großeltern", slug: "grosseltern", dir: "1.2 family/audio" },
  { word: "der Onkel", slug: "onkel", dir: "1.2 family/audio" },
  { word: "die Tante", slug: "tante", dir: "1.2 family/audio" },
  { word: "der Cousin", slug: "cousin", dir: "1.2 family/audio" },
  { word: "die Cousine", slug: "cousine", dir: "1.2 family/audio" },
  { word: "der Ehemann", slug: "ehemann", dir: "1.2 family/audio" },
  { word: "die Ehefrau", slug: "ehefrau", dir: "1.2 family/audio" },
  { word: "der Freund", slug: "freund", dir: "1.2 family/audio" },
  { word: "die Freundin", slug: "freundin", dir: "1.2 family/audio" },
  { word: "das Baby", slug: "baby", dir: "1.2 family/audio" },
  { word: "die Kinder", slug: "kinder", dir: "1.2 family/audio" },
  { word: "der Nachbar", slug: "nachbar", dir: "1.2 family/audio" },
  { word: "die Nachbarin", slug: "nachbarin", dir: "1.2 family/audio" },
  { word: "der Mensch", slug: "mensch", dir: "1.2 family/audio" },
  { word: "die Leute", slug: "leute", dir: "1.2 family/audio" },
  { word: "der Erwachsene", slug: "erwachsene", dir: "1.2 family/audio" },
  { word: "der Name", slug: "name", dir: "1.2 family/audio" },
  { word: "alt", slug: "alt", dir: "1.2 family/audio" },
  { word: "jung", slug: "jung", dir: "1.2 family/audio" },
  // Shared by 1.2 family and 1.4 home, so they stay flat under public/audio/.
  { word: "groß", slug: "gross" },
  { word: "klein", slug: "klein" },
  // Shared by 1.3 food / 1.4 home and 1.5 weather, so they stay flat too.
  { word: "schlecht", slug: "schlecht" },
  { word: "heiß", slug: "heiss" },
  { word: "kalt", slug: "kalt" },
  { word: "schön", slug: "schoen" },
  // Shared by 1.3 food and 1.6 hobbies.
  { word: "kochen", slug: "kochen" },
  { word: "nett", slug: "nett", dir: "1.2 family/audio" },
  { word: "freundlich", slug: "freundlich", dir: "1.2 family/audio" },
  { word: "verheiratet", slug: "verheiratet", dir: "1.2 family/audio" },
  { word: "ledig", slug: "ledig", dir: "1.2 family/audio" },
  { word: "zusammen", slug: "zusammen", dir: "1.2 family/audio" },
  { word: "allein", slug: "allein", dir: "1.2 family/audio" },
  { word: "das Essen", slug: "essen", dir: "1.3 food/audio" },
  { word: "das Frühstück", slug: "fruehstueck", dir: "1.3 food/audio" },
  { word: "das Mittagessen", slug: "mittagessen", dir: "1.3 food/audio" },
  { word: "das Abendessen", slug: "abendessen", dir: "1.3 food/audio" },
  { word: "das Brot", slug: "brot", dir: "1.3 food/audio" },
  { word: "das Brötchen", slug: "broetchen", dir: "1.3 food/audio" },
  { word: "der Reis", slug: "reis", dir: "1.3 food/audio" },
  { word: "die Nudeln", slug: "nudeln", dir: "1.3 food/audio" },
  { word: "die Kartoffel", slug: "kartoffel", dir: "1.3 food/audio" },
  { word: "das Fleisch", slug: "fleisch", dir: "1.3 food/audio" },
  { word: "das Hähnchen", slug: "haehnchen", dir: "1.3 food/audio" },
  { word: "der Fisch", slug: "fisch", dir: "1.3 food/audio" },
  { word: "das Ei", slug: "ei", dir: "1.3 food/audio" },
  { word: "die Wurst", slug: "wurst", dir: "1.3 food/audio" },
  { word: "der Käse", slug: "kaese", dir: "1.3 food/audio" },
  { word: "die Suppe", slug: "suppe", dir: "1.3 food/audio" },
  { word: "der Salat", slug: "salat", dir: "1.3 food/audio" },
  { word: "das Gemüse", slug: "gemuese", dir: "1.3 food/audio" },
  { word: "das Obst", slug: "obst", dir: "1.3 food/audio" },
  { word: "der Apfel", slug: "apfel", dir: "1.3 food/audio" },
  { word: "die Banane", slug: "banane", dir: "1.3 food/audio" },
  { word: "die Orange", slug: "orange", dir: "1.3 food/audio" },
  { word: "die Tomate", slug: "tomate", dir: "1.3 food/audio" },
  { word: "die Zwiebel", slug: "zwiebel", dir: "1.3 food/audio" },
  { word: "die Karotte", slug: "karotte", dir: "1.3 food/audio" },
  { word: "die Milch", slug: "milch", dir: "1.3 food/audio" },
  { word: "das Wasser", slug: "wasser", dir: "1.3 food/audio" },
  { word: "der Kaffee", slug: "kaffee", dir: "1.3 food/audio" },
  { word: "der Tee", slug: "tee", dir: "1.3 food/audio" },
  { word: "der Saft", slug: "saft", dir: "1.3 food/audio" },
  { word: "das Bier", slug: "bier", dir: "1.3 food/audio" },
  { word: "der Wein", slug: "wein", dir: "1.3 food/audio" },
  { word: "der Zucker", slug: "zucker", dir: "1.3 food/audio" },
  { word: "das Salz", slug: "salz", dir: "1.3 food/audio" },
  { word: "der Pfeffer", slug: "pfeffer", dir: "1.3 food/audio" },
  { word: "der Kuchen", slug: "kuchen", dir: "1.3 food/audio" },
  { word: "das Eis", slug: "eis", dir: "1.3 food/audio" },
  { word: "die Schokolade", slug: "schokolade", dir: "1.3 food/audio" },
  { word: "das Restaurant", slug: "restaurant", dir: "1.3 food/audio" },
  { word: "das Café", slug: "cafe", dir: "1.3 food/audio" },
  { word: "die Speisekarte", slug: "speisekarte", dir: "1.3 food/audio" },
  { word: "die Rechnung", slug: "rechnung", dir: "1.3 food/audio" },
  { word: "der Hunger", slug: "hunger", dir: "1.3 food/audio" },
  { word: "der Durst", slug: "durst", dir: "1.3 food/audio" },
  { word: "lecker", slug: "lecker", dir: "1.3 food/audio" },
  { word: "gut", slug: "gut", dir: "1.3 food/audio" },
  { word: "essen", slug: "essen-verb", dir: "1.3 food/audio" },
  { word: "trinken", slug: "trinken", dir: "1.3 food/audio" },
  { word: "bestellen", slug: "bestellen", dir: "1.3 food/audio" },
  { word: "bezahlen", slug: "bezahlen", dir: "1.3 food/audio" },
  { word: "schmecken", slug: "schmecken", dir: "1.3 food/audio" },
  { word: "das Haus", slug: "haus", dir: "1.4 home/audio" },
  { word: "die Wohnung", slug: "wohnung", dir: "1.4 home/audio" },
  { word: "das Zimmer", slug: "zimmer", dir: "1.4 home/audio" },
  { word: "das Schlafzimmer", slug: "schlafzimmer", dir: "1.4 home/audio" },
  { word: "das Wohnzimmer", slug: "wohnzimmer", dir: "1.4 home/audio" },
  { word: "das Badezimmer", slug: "badezimmer", dir: "1.4 home/audio" },
  { word: "die Küche", slug: "kueche", dir: "1.4 home/audio" },
  { word: "der Flur", slug: "flur", dir: "1.4 home/audio" },
  { word: "der Balkon", slug: "balkon", dir: "1.4 home/audio" },
  { word: "der Garten", slug: "garten", dir: "1.4 home/audio" },
  { word: "die Tür", slug: "tuer", dir: "1.4 home/audio" },
  { word: "das Fenster", slug: "fenster", dir: "1.4 home/audio" },
  { word: "die Wand", slug: "wand", dir: "1.4 home/audio" },
  { word: "der Boden", slug: "boden", dir: "1.4 home/audio" },
  { word: "die Treppe", slug: "treppe", dir: "1.4 home/audio" },
  { word: "der Tisch", slug: "tisch", dir: "1.4 home/audio" },
  { word: "der Stuhl", slug: "stuhl", dir: "1.4 home/audio" },
  { word: "das Bett", slug: "bett", dir: "1.4 home/audio" },
  { word: "das Sofa", slug: "sofa", dir: "1.4 home/audio" },
  { word: "der Schrank", slug: "schrank", dir: "1.4 home/audio" },
  { word: "das Regal", slug: "regal", dir: "1.4 home/audio" },
  { word: "die Lampe", slug: "lampe", dir: "1.4 home/audio" },
  { word: "der Fernseher", slug: "fernseher", dir: "1.4 home/audio" },
  { word: "der Kühlschrank", slug: "kuehlschrank", dir: "1.4 home/audio" },
  { word: "der Herd", slug: "herd", dir: "1.4 home/audio" },
  { word: "der Ofen", slug: "ofen", dir: "1.4 home/audio" },
  { word: "die Waschmaschine", slug: "waschmaschine", dir: "1.4 home/audio" },
  { word: "die Dusche", slug: "dusche", dir: "1.4 home/audio" },
  { word: "die Badewanne", slug: "badewanne", dir: "1.4 home/audio" },
  { word: "die Toilette", slug: "toilette", dir: "1.4 home/audio" },
  { word: "der Spiegel", slug: "spiegel", dir: "1.4 home/audio" },
  { word: "der Schlüssel", slug: "schluessel", dir: "1.4 home/audio" },
  { word: "die Tasche", slug: "tasche", dir: "1.4 home/audio" },
  { word: "das Handy", slug: "handy", dir: "1.4 home/audio" },
  { word: "der Computer", slug: "computer", dir: "1.4 home/audio" },
  { word: "sauber", slug: "sauber", dir: "1.4 home/audio" },
  { word: "schmutzig", slug: "schmutzig", dir: "1.4 home/audio" },
  { word: "bequem", slug: "bequem", dir: "1.4 home/audio" },
  { word: "wohnen", slug: "wohnen", dir: "1.4 home/audio" },
  { word: "öffnen", slug: "oeffnen", dir: "1.4 home/audio" },
  { word: "schließen", slug: "schliessen", dir: "1.4 home/audio" },
  { word: "putzen", slug: "putzen", dir: "1.4 home/audio" },
  { word: "schlafen", slug: "schlafen", dir: "1.4 home/audio" },
  { word: "das Wetter", slug: "wetter", dir: "1.5 weather/audio" },
  { word: "die Sonne", slug: "sonne", dir: "1.5 weather/audio" },
  { word: "der Regen", slug: "regen", dir: "1.5 weather/audio" },
  { word: "der Schnee", slug: "schnee", dir: "1.5 weather/audio" },
  { word: "der Wind", slug: "wind", dir: "1.5 weather/audio" },
  { word: "die Wolke", slug: "wolke", dir: "1.5 weather/audio" },
  { word: "der Himmel", slug: "himmel", dir: "1.5 weather/audio" },
  { word: "der Nebel", slug: "nebel", dir: "1.5 weather/audio" },
  { word: "das Gewitter", slug: "gewitter", dir: "1.5 weather/audio" },
  { word: "der Sturm", slug: "sturm", dir: "1.5 weather/audio" },
  { word: "die Temperatur", slug: "temperatur", dir: "1.5 weather/audio" },
  { word: "der Grad", slug: "grad", dir: "1.5 weather/audio" },
  { word: "der Sommer", slug: "sommer", dir: "1.5 weather/audio" },
  { word: "der Winter", slug: "winter", dir: "1.5 weather/audio" },
  { word: "der Frühling", slug: "fruehling", dir: "1.5 weather/audio" },
  { word: "der Herbst", slug: "herbst", dir: "1.5 weather/audio" },
  { word: "sonnig", slug: "sonnig", dir: "1.5 weather/audio" },
  { word: "regnerisch", slug: "regnerisch", dir: "1.5 weather/audio" },
  { word: "windig", slug: "windig", dir: "1.5 weather/audio" },
  { word: "bewölkt", slug: "bewoelkt", dir: "1.5 weather/audio" },
  { word: "neblig", slug: "neblig", dir: "1.5 weather/audio" },
  { word: "warm", slug: "warm", dir: "1.5 weather/audio" },
  { word: "kühl", slug: "kuehl", dir: "1.5 weather/audio" },
  { word: "trocken", slug: "trocken", dir: "1.5 weather/audio" },
  { word: "nass", slug: "nass", dir: "1.5 weather/audio" },
  { word: "klar", slug: "klar", dir: "1.5 weather/audio" },
  { word: "regnen", slug: "regnen", dir: "1.5 weather/audio" },
  { word: "schneien", slug: "schneien", dir: "1.5 weather/audio" },
  { word: "frieren", slug: "frieren", dir: "1.5 weather/audio" },
  { word: "scheinen", slug: "scheinen", dir: "1.5 weather/audio" },
  { word: "das Hobby", slug: "hobby", dir: "1.6 hobbies/audio" },
  { word: "die Hobbys", slug: "hobbys", dir: "1.6 hobbies/audio" },
  { word: "der Sport", slug: "sport", dir: "1.6 hobbies/audio" },
  { word: "das Fußballspielen", slug: "fussballspielen", dir: "1.6 hobbies/audio" },
  { word: "das Schwimmen", slug: "schwimmen", dir: "1.6 hobbies/audio" },
  { word: "das Laufen", slug: "laufen", dir: "1.6 hobbies/audio" },
  { word: "das Radfahren", slug: "radfahren", dir: "1.6 hobbies/audio" },
  { word: "das Wandern", slug: "wandern", dir: "1.6 hobbies/audio" },
  { word: "das Tanzen", slug: "tanzen", dir: "1.6 hobbies/audio" },
  { word: "das Singen", slug: "singen", dir: "1.6 hobbies/audio" },
  { word: "das Kochen", slug: "kochen", dir: "1.6 hobbies/audio" },
  { word: "das Backen", slug: "backen", dir: "1.6 hobbies/audio" },
  { word: "das Lesen", slug: "lesen", dir: "1.6 hobbies/audio" },
  { word: "das Schreiben", slug: "schreiben", dir: "1.6 hobbies/audio" },
  { word: "das Zeichnen", slug: "zeichnen", dir: "1.6 hobbies/audio" },
  { word: "das Malen", slug: "malen", dir: "1.6 hobbies/audio" },
  { word: "das Fotografieren", slug: "fotografieren", dir: "1.6 hobbies/audio" },
  { word: "das Reisen", slug: "reisen", dir: "1.6 hobbies/audio" },
  { word: "das Angeln", slug: "angeln", dir: "1.6 hobbies/audio" },
  { word: "das Spielen", slug: "spielen", dir: "1.6 hobbies/audio" },
  { word: "die Musik", slug: "musik", dir: "1.6 hobbies/audio" },
  { word: "der Film", slug: "film", dir: "1.6 hobbies/audio" },
  { word: "das Computerspiel", slug: "computerspiel", dir: "1.6 hobbies/audio" },
  { word: "das Videospiel", slug: "videospiel", dir: "1.6 hobbies/audio" },
  { word: "das Instrument", slug: "instrument", dir: "1.6 hobbies/audio" },
  { word: "die Gitarre", slug: "gitarre", dir: "1.6 hobbies/audio" },
  { word: "das Klavier", slug: "klavier", dir: "1.6 hobbies/audio" },
  { word: "spielen", slug: "spielen-verb", dir: "1.6 hobbies/audio" },
  { word: "lesen", slug: "lesen-verb", dir: "1.6 hobbies/audio" },
  { word: "schreiben", slug: "schreiben-verb", dir: "1.6 hobbies/audio" },
  { word: "schwimmen", slug: "schwimmen-verb", dir: "1.6 hobbies/audio" },
  { word: "laufen", slug: "laufen-verb", dir: "1.6 hobbies/audio" },
  { word: "tanzen", slug: "tanzen-verb", dir: "1.6 hobbies/audio" },
  { word: "singen", slug: "singen-verb", dir: "1.6 hobbies/audio" },
  { word: "backen", slug: "backen-verb", dir: "1.6 hobbies/audio" },
  { word: "reisen", slug: "reisen-verb", dir: "1.6 hobbies/audio" },
  { word: "wandern", slug: "wandern-verb", dir: "1.6 hobbies/audio" },
  { word: "fotografieren", slug: "fotografieren-verb", dir: "1.6 hobbies/audio" },
  { word: "zeichnen", slug: "zeichnen-verb", dir: "1.6 hobbies/audio" },
  { word: "malen", slug: "malen-verb", dir: "1.6 hobbies/audio" },
  { word: "hören", slug: "hoeren", dir: "1.6 hobbies/audio" },
  { word: "sehen", slug: "sehen", dir: "1.6 hobbies/audio" },
  { word: "machen", slug: "machen", dir: "1.6 hobbies/audio" },
  { word: "der Beruf", slug: "beruf", dir: "1.7 jobs/audio" },
  { word: "die Arbeit", slug: "arbeit", dir: "1.7 jobs/audio" },
  { word: "der Arzt", slug: "arzt", dir: "1.7 jobs/audio" },
  { word: "die Ärztin", slug: "aerztin", dir: "1.7 jobs/audio" },
  { word: "der Lehrer", slug: "lehrer", dir: "1.7 jobs/audio" },
  { word: "die Lehrerin", slug: "lehrerin", dir: "1.7 jobs/audio" },
  { word: "der Schüler", slug: "schueler", dir: "1.7 jobs/audio" },
  { word: "die Schülerin", slug: "schuelerin", dir: "1.7 jobs/audio" },
  { word: "der Student", slug: "student", dir: "1.7 jobs/audio" },
  { word: "die Studentin", slug: "studentin", dir: "1.7 jobs/audio" },
  { word: "der Ingenieur", slug: "ingenieur", dir: "1.7 jobs/audio" },
  { word: "die Ingenieurin", slug: "ingenieurin", dir: "1.7 jobs/audio" },
  { word: "der Programmierer", slug: "programmierer", dir: "1.7 jobs/audio" },
  { word: "die Programmiererin", slug: "programmiererin", dir: "1.7 jobs/audio" },
  { word: "der Verkäufer", slug: "verkaeufer", dir: "1.7 jobs/audio" },
  { word: "die Verkäuferin", slug: "verkaeuferin", dir: "1.7 jobs/audio" },
  { word: "der Koch", slug: "koch", dir: "1.7 jobs/audio" },
  { word: "die Köchin", slug: "koechin", dir: "1.7 jobs/audio" },
  { word: "der Kellner", slug: "kellner", dir: "1.7 jobs/audio" },
  { word: "die Kellnerin", slug: "kellnerin", dir: "1.7 jobs/audio" },
  { word: "der Fahrer", slug: "fahrer", dir: "1.7 jobs/audio" },
  { word: "die Fahrerin", slug: "fahrerin", dir: "1.7 jobs/audio" },
  { word: "der Polizist", slug: "polizist", dir: "1.7 jobs/audio" },
  { word: "die Polizistin", slug: "polizistin", dir: "1.7 jobs/audio" },
  { word: "der Mechaniker", slug: "mechaniker", dir: "1.7 jobs/audio" },
  { word: "die Mechanikerin", slug: "mechanikerin", dir: "1.7 jobs/audio" },
  { word: "der Bäcker", slug: "baecker", dir: "1.7 jobs/audio" },
  { word: "die Bäckerin", slug: "baeckerin", dir: "1.7 jobs/audio" },
  { word: "der Journalist", slug: "journalist", dir: "1.7 jobs/audio" },
  { word: "die Journalistin", slug: "journalistin", dir: "1.7 jobs/audio" },
  { word: "der Musiker", slug: "musiker", dir: "1.7 jobs/audio" },
  { word: "die Musikerin", slug: "musikerin", dir: "1.7 jobs/audio" },
  { word: "der Künstler", slug: "kuenstler", dir: "1.7 jobs/audio" },
  { word: "die Künstlerin", slug: "kuenstlerin", dir: "1.7 jobs/audio" },
  { word: "der Krankenpfleger", slug: "krankenpfleger", dir: "1.7 jobs/audio" },
  { word: "die Krankenpflegerin", slug: "krankenpflegerin", dir: "1.7 jobs/audio" },
  { word: "der Zahnarzt", slug: "zahnarzt", dir: "1.7 jobs/audio" },
  { word: "die Zahnärztin", slug: "zahnaerztin", dir: "1.7 jobs/audio" },
  { word: "der Apotheker", slug: "apotheker", dir: "1.7 jobs/audio" },
  { word: "die Apothekerin", slug: "apothekerin", dir: "1.7 jobs/audio" },
  { word: "der Elektriker", slug: "elektriker", dir: "1.7 jobs/audio" },
  { word: "die Elektrikerin", slug: "elektrikerin", dir: "1.7 jobs/audio" },
  { word: "der Friseur", slug: "friseur", dir: "1.7 jobs/audio" },
  { word: "die Friseurin", slug: "friseurin", dir: "1.7 jobs/audio" },
  { word: "der Bauer", slug: "bauer", dir: "1.7 jobs/audio" },
  { word: "die Bäuerin", slug: "baeuerin", dir: "1.7 jobs/audio" },
  { word: "der Fotograf", slug: "fotograf", dir: "1.7 jobs/audio" },
  { word: "die Fotografin", slug: "fotografin", dir: "1.7 jobs/audio" },
  { word: "der Designer", slug: "designer", dir: "1.7 jobs/audio" },
  { word: "die Designerin", slug: "designerin", dir: "1.7 jobs/audio" },
  { word: "der Manager", slug: "manager", dir: "1.7 jobs/audio" },
  { word: "die Managerin", slug: "managerin", dir: "1.7 jobs/audio" },
  { word: "der Job", slug: "job", dir: "1.7 jobs/audio" },
  { word: "arbeiten", slug: "arbeiten", dir: "1.7 jobs/audio" },
  { word: "lernen", slug: "lernen", dir: "1.7 jobs/audio" },
  { word: "studieren", slug: "studieren", dir: "1.7 jobs/audio" },
  { word: "die Firma", slug: "firma", dir: "1.7 jobs/audio" },
  { word: "das Büro", slug: "buero", dir: "1.7 jobs/audio" },
  { word: "die Schule", slug: "schule", dir: "1.7 jobs/audio" },
  { word: "die Universität", slug: "universitaet", dir: "1.7 jobs/audio" },
  { word: "das Krankenhaus", slug: "krankenhaus", dir: "1.7 jobs/audio" },
  { word: "das Geschäft", slug: "geschaeft", dir: "1.7 jobs/audio" },
  { word: "der Arbeitsplatz", slug: "arbeitsplatz", dir: "1.7 jobs/audio" },
  { word: "der Kollege", slug: "kollege", dir: "1.7 jobs/audio" },
  { word: "die Kollegin", slug: "kollegin", dir: "1.7 jobs/audio" },
  { word: "der Chef", slug: "chef", dir: "1.7 jobs/audio" },
  { word: "die Chefin", slug: "chefin", dir: "1.7 jobs/audio" },
  { word: "das Team", slug: "team", dir: "1.7 jobs/audio" },
  { word: "der Mitarbeiter", slug: "mitarbeiter", dir: "1.7 jobs/audio" },
  { word: "die Mitarbeiterin", slug: "mitarbeiterin", dir: "1.7 jobs/audio" },
  { word: "der Vorname", slug: "vorname", dir: "1.8 personal information/audio" },
  { word: "der Nachname", slug: "nachname", dir: "1.8 personal information/audio" },
  { word: "das Alter", slug: "alter", dir: "1.8 personal information/audio" },
  { word: "der Geburtstag", slug: "geburtstag", dir: "1.8 personal information/audio" },
  { word: "das Geburtsdatum", slug: "geburtsdatum", dir: "1.8 personal information/audio" },
  { word: "der Geburtsort", slug: "geburtsort", dir: "1.8 personal information/audio" },
  { word: "der Wohnort", slug: "wohnort", dir: "1.8 personal information/audio" },
  { word: "die Adresse", slug: "adresse", dir: "1.8 personal information/audio" },
  { word: "die Straße", slug: "strasse", dir: "1.8 personal information/audio" },
  { word: "die Hausnummer", slug: "hausnummer", dir: "1.8 personal information/audio" },
  { word: "die Telefonnummer", slug: "telefonnummer", dir: "1.8 personal information/audio" },
  { word: "die E-Mail-Adresse", slug: "e-mail-adresse", dir: "1.8 personal information/audio" },
  { word: "die Stadt", slug: "stadt", dir: "1.8 personal information/audio" },
  { word: "das Land", slug: "land", dir: "1.8 personal information/audio" },
  { word: "die Nationalität", slug: "nationalitaet", dir: "1.8 personal information/audio" },
  { word: "die Sprache", slug: "sprache", dir: "1.8 personal information/audio" },
  { word: "die Muttersprache", slug: "muttersprache", dir: "1.8 personal information/audio" },
  { word: "die Person", slug: "person", dir: "1.8 personal information/audio" },
  { word: "der Mann", slug: "mann", dir: "1.8 personal information/audio" },
  { word: "die Frau", slug: "frau", dir: "1.8 personal information/audio" },
  { word: "das Kind", slug: "kind", dir: "1.8 personal information/audio" },
  { word: "der Junge", slug: "junge", dir: "1.8 personal information/audio" },
  { word: "das Mädchen", slug: "maedchen", dir: "1.8 personal information/audio" },
  { word: "der Arbeiter", slug: "arbeiter", dir: "1.8 personal information/audio" },
  { word: "heißen", slug: "heissen", dir: "1.8 personal information/audio" },
  { word: "sein", slug: "sein", dir: "1.8 personal information/audio" },
  { word: "kommen", slug: "kommen", dir: "1.8 personal information/audio" },
  { word: "geboren", slug: "geboren", dir: "1.8 personal information/audio" },
  { word: "der Laden", slug: "laden", dir: "1.9 shopping/audio" },
  { word: "der Supermarkt", slug: "supermarkt", dir: "1.9 shopping/audio" },
  { word: "der Markt", slug: "markt", dir: "1.9 shopping/audio" },
  { word: "das Einkaufszentrum", slug: "einkaufszentrum", dir: "1.9 shopping/audio" },
  { word: "der Preis", slug: "preis", dir: "1.9 shopping/audio" },
  { word: "das Geld", slug: "geld", dir: "1.9 shopping/audio" },
  { word: "der Euro", slug: "euro", dir: "1.9 shopping/audio" },
  { word: "der Kunde", slug: "kunde", dir: "1.9 shopping/audio" },
  { word: "die Kundin", slug: "kundin", dir: "1.9 shopping/audio" },
  { word: "die Kasse", slug: "kasse", dir: "1.9 shopping/audio" },
  { word: "die Größe", slug: "groesse", dir: "1.9 shopping/audio" },
  { word: "die Farbe", slug: "farbe", dir: "1.9 shopping/audio" },
  { word: "das Kleid", slug: "kleid", dir: "1.9 shopping/audio" },
  { word: "das Hemd", slug: "hemd", dir: "1.9 shopping/audio" },
  { word: "die Hose", slug: "hose", dir: "1.9 shopping/audio" },
  { word: "die Jacke", slug: "jacke", dir: "1.9 shopping/audio" },
  { word: "der Mantel", slug: "mantel", dir: "1.9 shopping/audio" },
  { word: "der Schuh", slug: "schuh", dir: "1.9 shopping/audio" },
  { word: "die Schuhe", slug: "schuhe", dir: "1.9 shopping/audio" },
  { word: "das T-Shirt", slug: "t-shirt", dir: "1.9 shopping/audio" },
  { word: "die Kleidung", slug: "kleidung", dir: "1.9 shopping/audio" },
  { word: "billig", slug: "billig", dir: "1.9 shopping/audio" },
  { word: "teuer", slug: "teuer", dir: "1.9 shopping/audio" },
  { word: "günstig", slug: "guenstig", dir: "1.9 shopping/audio" },
  { word: "neu", slug: "neu", dir: "1.9 shopping/audio" },
  { word: "rot", slug: "rot", dir: "1.9 shopping/audio" },
  { word: "blau", slug: "blau", dir: "1.9 shopping/audio" },
  { word: "grün", slug: "gruen", dir: "1.9 shopping/audio" },
  { word: "gelb", slug: "gelb", dir: "1.9 shopping/audio" },
  { word: "schwarz", slug: "schwarz", dir: "1.9 shopping/audio" },
  { word: "weiß", slug: "weiss", dir: "1.9 shopping/audio" },
  { word: "kaufen", slug: "kaufen", dir: "1.9 shopping/audio" },
  { word: "verkaufen", slug: "verkaufen", dir: "1.9 shopping/audio" },
  { word: "suchen", slug: "suchen", dir: "1.9 shopping/audio" },
  { word: "finden", slug: "finden", dir: "1.9 shopping/audio" },
  { word: "brauchen", slug: "brauchen", dir: "1.9 shopping/audio" },
  { word: "kosten", slug: "kosten", dir: "1.9 shopping/audio" },
  { word: "nehmen", slug: "nehmen", dir: "1.9 shopping/audio" },
  { word: "geben", slug: "geben", dir: "1.9 shopping/audio" },
  { word: "haben", slug: "haben", dir: "1.9 shopping/audio" },
  { word: "die Zeit", slug: "zeit", dir: "1.10 time/audio" },
  { word: "die Uhr", slug: "uhr", dir: "1.10 time/audio" },
  { word: "die Stunde", slug: "stunde", dir: "1.10 time/audio" },
  { word: "die Minute", slug: "minute", dir: "1.10 time/audio" },
  { word: "die Sekunde", slug: "sekunde", dir: "1.10 time/audio" },
  { word: "der Tag", slug: "tag", dir: "1.10 time/audio" },
  { word: "die Woche", slug: "woche", dir: "1.10 time/audio" },
  { word: "der Monat", slug: "monat", dir: "1.10 time/audio" },
  { word: "das Jahr", slug: "jahr", dir: "1.10 time/audio" },
  { word: "der Morgen", slug: "der-morgen", dir: "1.10 time/audio" },
  { word: "der Nachmittag", slug: "nachmittag", dir: "1.10 time/audio" },
  { word: "der Abend", slug: "abend", dir: "1.10 time/audio" },
  { word: "die Nacht", slug: "nacht", dir: "1.10 time/audio" },
  { word: "heute", slug: "heute", dir: "1.10 time/audio" },
  { word: "morgen", slug: "morgen", dir: "1.10 time/audio" },
  { word: "gestern", slug: "gestern", dir: "1.10 time/audio" },
  { word: "jetzt", slug: "jetzt", dir: "1.10 time/audio" },
  { word: "später", slug: "spaeter", dir: "1.10 time/audio" },
  { word: "früh", slug: "frueh", dir: "1.10 time/audio" },
  { word: "spät", slug: "spaet", dir: "1.10 time/audio" },
  { word: "morgens", slug: "morgens", dir: "1.10 time/audio" },
  { word: "mittags", slug: "mittags", dir: "1.10 time/audio" },
  { word: "nachmittags", slug: "nachmittags", dir: "1.10 time/audio" },
  { word: "abends", slug: "abends", dir: "1.10 time/audio" },
  { word: "nachts", slug: "nachts", dir: "1.10 time/audio" },
  { word: "zuerst", slug: "zuerst", dir: "1.10 time/audio" },
  { word: "dann", slug: "dann", dir: "1.10 time/audio" },
  { word: "immer", slug: "immer", dir: "1.10 time/audio" },
  { word: "Montag", slug: "montag", dir: "1.10 time/audio" },
  { word: "Dienstag", slug: "dienstag", dir: "1.10 time/audio" },
  { word: "Mittwoch", slug: "mittwoch", dir: "1.10 time/audio" },
  { word: "Donnerstag", slug: "donnerstag", dir: "1.10 time/audio" },
  { word: "Freitag", slug: "freitag", dir: "1.10 time/audio" },
  { word: "Samstag", slug: "samstag", dir: "1.10 time/audio" },
  { word: "Sonntag", slug: "sonntag", dir: "1.10 time/audio" },
  { word: "oft", slug: "oft", dir: "1.10 time/audio" },
  { word: "manchmal", slug: "manchmal", dir: "1.10 time/audio" },
  { word: "Januar", slug: "januar", dir: "1.10 time/audio" },
  { word: "Februar", slug: "februar", dir: "1.10 time/audio" },
  { word: "März", slug: "maerz", dir: "1.10 time/audio" },
  { word: "April", slug: "april", dir: "1.10 time/audio" },
  { word: "Mai", slug: "mai", dir: "1.10 time/audio" },
  { word: "Juni", slug: "juni", dir: "1.10 time/audio" },
  { word: "Juli", slug: "juli", dir: "1.10 time/audio" },
  { word: "August", slug: "august", dir: "1.10 time/audio" },
  { word: "September", slug: "september", dir: "1.10 time/audio" },
  { word: "Oktober", slug: "oktober", dir: "1.10 time/audio" },
  { word: "November", slug: "november", dir: "1.10 time/audio" },
  { word: "Dezember", slug: "dezember", dir: "1.10 time/audio" },
  { word: "nie", slug: "nie", dir: "1.10 time/audio" },
  { word: "der Verkehr", slug: "verkehr", dir: "1.11 transport/audio" },
  { word: "das Auto", slug: "auto", dir: "1.11 transport/audio" },
  { word: "der Bus", slug: "bus", dir: "1.11 transport/audio" },
  { word: "der Zug", slug: "zug", dir: "1.11 transport/audio" },
  { word: "die Bahn", slug: "bahn", dir: "1.11 transport/audio" },
  { word: "die Straßenbahn", slug: "strassenbahn", dir: "1.11 transport/audio" },
  { word: "die U-Bahn", slug: "u-bahn", dir: "1.11 transport/audio" },
  { word: "das Taxi", slug: "taxi", dir: "1.11 transport/audio" },
  { word: "das Fahrrad", slug: "fahrrad", dir: "1.11 transport/audio" },
  { word: "das Motorrad", slug: "motorrad", dir: "1.11 transport/audio" },
  { word: "das Flugzeug", slug: "flugzeug", dir: "1.11 transport/audio" },
  { word: "der Flughafen", slug: "flughafen", dir: "1.11 transport/audio" },
  { word: "der Bahnhof", slug: "bahnhof", dir: "1.11 transport/audio" },
  { word: "die Haltestelle", slug: "haltestelle", dir: "1.11 transport/audio" },
  { word: "der Weg", slug: "weg", dir: "1.11 transport/audio" },
  { word: "die Kreuzung", slug: "kreuzung", dir: "1.11 transport/audio" },
  { word: "die Ampel", slug: "ampel", dir: "1.11 transport/audio" },
  { word: "die Karte", slug: "karte", dir: "1.11 transport/audio" },
  { word: "das Ticket", slug: "ticket", dir: "1.11 transport/audio" },
  { word: "die Fahrkarte", slug: "fahrkarte", dir: "1.11 transport/audio" },
  { word: "die Richtung", slug: "richtung", dir: "1.11 transport/audio" },
  { word: "links", slug: "links", dir: "1.11 transport/audio" },
  { word: "rechts", slug: "rechts", dir: "1.11 transport/audio" },
  { word: "geradeaus", slug: "geradeaus", dir: "1.11 transport/audio" },
  { word: "zurück", slug: "zurueck", dir: "1.11 transport/audio" },
  { word: "hier", slug: "hier", dir: "1.11 transport/audio" },
  { word: "dort", slug: "dort", dir: "1.11 transport/audio" },
  { word: "neben", slug: "neben", dir: "1.11 transport/audio" },
  { word: "gegenüber", slug: "gegenueber", dir: "1.11 transport/audio" },
  { word: "vor", slug: "vor", dir: "1.11 transport/audio" },
  { word: "hinter", slug: "hinter", dir: "1.11 transport/audio" },
  { word: "zwischen", slug: "zwischen", dir: "1.11 transport/audio" },
  { word: "an", slug: "an", dir: "1.11 transport/audio" },
  { word: "auf", slug: "auf", dir: "1.11 transport/audio" },
  { word: "in", slug: "in", dir: "1.11 transport/audio" },
  { word: "nach", slug: "nach", dir: "1.11 transport/audio" },
  { word: "aus", slug: "aus", dir: "1.11 transport/audio" },
  { word: "fahren", slug: "fahren", dir: "1.11 transport/audio" },
  { word: "gehen", slug: "gehen", dir: "1.11 transport/audio" },
  { word: "fliegen", slug: "fliegen", dir: "1.11 transport/audio" },
  { word: "abfahren", slug: "abfahren", dir: "1.11 transport/audio" },
  { word: "ankommen", slug: "ankommen", dir: "1.11 transport/audio" },
  { word: "einsteigen", slug: "einsteigen", dir: "1.11 transport/audio" },
  { word: "aussteigen", slug: "aussteigen", dir: "1.11 transport/audio" },
  { word: "warten", slug: "warten", dir: "1.11 transport/audio" },
  { word: "zeigen", slug: "zeigen", dir: "1.11 transport/audio" },
  { word: "die Pause", slug: "pause", dir: "1.12 work and school/audio" },
  { word: "die Klasse", slug: "klasse", dir: "1.12 work and school/audio" },
  { word: "der Kurs", slug: "kurs", dir: "1.12 work and school/audio" },
  { word: "das Fach", slug: "fach", dir: "1.12 work and school/audio" },
  { word: "die Prüfung", slug: "pruefung", dir: "1.12 work and school/audio" },
  { word: "die Aufgabe", slug: "aufgabe", dir: "1.12 work and school/audio" },
  { word: "das Heft", slug: "heft", dir: "1.12 work and school/audio" },
  { word: "der Stift", slug: "stift", dir: "1.12 work and school/audio" },
  { word: "die Freizeit", slug: "freizeit", dir: "1.12 work and school/audio" },
  { word: "verstehen", slug: "verstehen", dir: "1.12 work and school/audio" },
  { word: "sprechen", slug: "sprechen", dir: "1.12 work and school/audio" },
  { word: "fragen", slug: "fragen", dir: "1.12 work and school/audio" },
  { word: "antworten", slug: "antworten", dir: "1.12 work and school/audio" },
  { word: "erklären", slug: "erklaeren", dir: "1.12 work and school/audio" },
  { word: "beginnen", slug: "beginnen", dir: "1.12 work and school/audio" },
  { word: "enden", slug: "enden", dir: "1.12 work and school/audio" },
  { word: "verdienen", slug: "verdienen", dir: "1.12 work and school/audio" },
  { word: "die Gesundheit", slug: "gesundheit", dir: "1.13 health/audio" },
  { word: "der Körper", slug: "koerper", dir: "1.13 health/audio" },
  { word: "der Kopf", slug: "kopf", dir: "1.13 health/audio" },
  { word: "das Gesicht", slug: "gesicht", dir: "1.13 health/audio" },
  { word: "das Auge", slug: "auge", dir: "1.13 health/audio" },
  { word: "das Ohr", slug: "ohr", dir: "1.13 health/audio" },
  { word: "die Nase", slug: "nase", dir: "1.13 health/audio" },
  { word: "der Mund", slug: "mund", dir: "1.13 health/audio" },
  { word: "der Zahn", slug: "zahn", dir: "1.13 health/audio" },
  { word: "der Hals", slug: "hals", dir: "1.13 health/audio" },
  { word: "die Hand", slug: "hand", dir: "1.13 health/audio" },
  { word: "der Arm", slug: "arm", dir: "1.13 health/audio" },
  { word: "das Bein", slug: "bein", dir: "1.13 health/audio" },
  { word: "der Fuß", slug: "fuss", dir: "1.13 health/audio" },
  { word: "der Rücken", slug: "ruecken", dir: "1.13 health/audio" },
  { word: "der Bauch", slug: "bauch", dir: "1.13 health/audio" },
  { word: "die Apotheke", slug: "apotheke", dir: "1.13 health/audio" },
  { word: "die Medizin", slug: "medizin", dir: "1.13 health/audio" },
  { word: "das Medikament", slug: "medikament", dir: "1.13 health/audio" },
  { word: "der Schmerz", slug: "schmerz", dir: "1.13 health/audio" },
  { word: "das Kopfweh", slug: "kopfweh", dir: "1.13 health/audio" },
  { word: "die Krankheit", slug: "krankheit", dir: "1.13 health/audio" },
  { word: "die Erkältung", slug: "erkaeltung", dir: "1.13 health/audio" },
  { word: "das Fieber", slug: "fieber", dir: "1.13 health/audio" },
  { word: "der Husten", slug: "husten", dir: "1.13 health/audio" },
  { word: "gesund", slug: "gesund", dir: "1.13 health/audio" },
  { word: "krank", slug: "krank", dir: "1.13 health/audio" },
  { word: "müde", slug: "muede", dir: "1.13 health/audio" },
  { word: "fit", slug: "fit", dir: "1.13 health/audio" },
  { word: "verletzt", slug: "verletzt", dir: "1.13 health/audio" },
  { word: "weh tun", slug: "weh-tun", dir: "1.13 health/audio" },
  { word: "fühlen", slug: "fuehlen", dir: "1.13 health/audio" },
  { word: "helfen", slug: "helfen", dir: "1.13 health/audio" },
];

// Full lesson-screen titles (e.g. "Was ist das?"), spoken when a kid taps the
// title. Same word/slug shape as WORDS — msedge-tts handles full sentences
// just as well as single words, so these render and manifest the same way.
const TITLES = [
  { word: "Was ist das?", slug: "title-was-ist-das" },
  { word: "Welches Bild ist das?", slug: "title-welches-bild-ist-das" },
  { word: "Was bedeutet das?", slug: "title-was-bedeutet-das" },
  { word: "Wie sagt man das auf Deutsch?", slug: "title-wie-sagt-man-das-auf-deutsch" },
  { word: "Welcher Artikel passt?", slug: "title-welcher-artikel-passt" },
  { word: "Baue das Wort", slug: "title-baue-das-wort" },
  { word: "Welcher Buchstabe fehlt?", slug: "title-welcher-buchstabe-fehlt" },
  { word: "Ordne die Buchstaben", slug: "title-ordne-die-buchstaben" },
  { word: "Was hörst du?", slug: "title-was-hoerst-du" },
  { word: "Welches Bild hörst du?", slug: "title-welches-bild-hoerst-du" },
  { word: "Finde die Paare", slug: "title-finde-die-paare" },
];

// The German alphabet, for the word-builder's letter tiles. `name` spells out
// how the letter is actually said in German (e.g. P -> "Peh", not the English
// "pee") as a normal German word/syllable, so the TTS engine's ordinary
// German pronunciation rules produce the right sound instead of relying on
// its (often English-biased) bare-letter reading.
//
// Note on E and I specifically: their letter names are long vowels ("ay",
// "ee"), but the obvious spellings "Eh" and "Ih" are also common German
// interjections ("eh?", "ih!") that real speech-recognition-trained TTS
// lexicons tend to read short/clipped, not as the long recitation vowel we
// want. "Ee"/"Ie" use German's standard long-vowel digraph spelling instead
// (as in "Idee", "wie") and aren't real standalone words, avoiding that
// ambiguity. (This TTS API doesn't support SSML for finer control — plain
// text is all it accepts.)
const LETTERS = [
  { letter: "A", name: "Ah" },
  { letter: "B", name: "Beh" },
  { letter: "C", name: "Zeh" },
  { letter: "D", name: "Deh" },
  { letter: "E", name: "Ee" },
  { letter: "F", name: "Ef" },
  { letter: "G", name: "Geh" },
  { letter: "H", name: "Hah" },
  { letter: "I", name: "Ie" },
  { letter: "J", name: "Jott" },
  { letter: "K", name: "Kah" },
  { letter: "L", name: "El" },
  { letter: "M", name: "Em" },
  { letter: "N", name: "En" },
  { letter: "O", name: "Oh" },
  { letter: "P", name: "Peh" },
  { letter: "Q", name: "Kuh" },
  { letter: "R", name: "Er" },
  { letter: "S", name: "Es" },
  { letter: "T", name: "Teh" },
  { letter: "U", name: "Uh" },
  { letter: "V", name: "Fau" },
  { letter: "W", name: "Weh" },
  { letter: "X", name: "Iks" },
  { letter: "Y", name: "Ypsilon" },
  { letter: "Z", name: "Zett" },
];

const force = process.argv.includes("--force");

async function synthesize(text, rate) {
  const tts = new MsEdgeTTS();
  await tts.setMetadata(VOICE, OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3);
  const { audioStream } = tts.toStream(text, { rate });
  const chunks = [];
  for await (const chunk of audioStream) chunks.push(chunk);
  return Buffer.concat(chunks);
}

async function writeIfMissing(filePath, label, text, rate) {
  if (existsSync(filePath) && !force) {
    console.log(`skip   ${label} (already exists, use --force to regenerate)`);
    return;
  }
  const buffer = await synthesize(text, rate);
  await writeFile(filePath, buffer);
  console.log(`wrote  ${label} (${buffer.length} bytes) — "${text}"`);
}

await mkdir(AUDIO_DIR, { recursive: true });
await mkdir(LETTERS_DIR, { recursive: true });

for (const { word, slug, dir } of [...WORDS, ...TITLES]) {
  const outDir = path.join(ROOT, "public", dir ?? "audio");
  await mkdir(outDir, { recursive: true });
  await writeIfMissing(
    path.join(outDir, `${slug}.mp3`),
    `${dir ?? "audio"}/${slug}.mp3`,
    word,
    "-15%",
  );
}

for (const { letter, name } of LETTERS) {
  const slug = letter.toLowerCase();
  await writeIfMissing(path.join(LETTERS_DIR, `${slug}.mp3`), `letters/${slug}.mp3`, name, "-10%");
}

const wordManifestBody = [...WORDS, ...TITLES]
  .map(({ word, slug, dir }) => `  ${JSON.stringify(word)}: "/${dir ?? "audio"}/${slug}.mp3",`)
  .join("\n");
await writeFile(
  WORD_MANIFEST_PATH,
  `// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Maps a full German word (with article) or lesson-screen title to its
// pronunciation audio file.
export const WORD_AUDIO: Record<string, string> = {
${wordManifestBody}
};
`,
);
console.log(`wrote  ${path.relative(ROOT, WORD_MANIFEST_PATH)}`);

const letterManifestBody = LETTERS.map(
  ({ letter }) => `  ${JSON.stringify(letter)}: "/audio/letters/${letter.toLowerCase()}.mp3",`,
).join("\n");
await writeFile(
  LETTER_MANIFEST_PATH,
  `// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Maps an uppercase German letter to its pronunciation audio file.
export const LETTER_AUDIO: Record<string, string> = {
${letterManifestBody}
};
`,
);
console.log(`wrote  ${path.relative(ROOT, LETTER_MANIFEST_PATH)}`);
