/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UebenRouteImport } from './routes/ueben'
import { Route as KursUnitIdIndexRouteImport } from './routes/kurs.$unitId.index'
import { Route as KursUnitIdLessonIdRouteImport } from './routes/kurs.$unitId.$lessonId'
import { Route as KursUnitIdCheckpointRouteImport } from './routes/kurs.$unitId.checkpoint'
import { Route as KursUnitIdGuideRouteImport } from './routes/kurs.$unitId.guide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UebenRoute = UebenRouteImport.update({
  id: '/ueben',
  path: '/ueben',
  getParentRoute: () => rootRouteImport,
} as any)
const KursUnitIdIndexRoute = KursUnitIdIndexRouteImport.update({
  id: '/kurs/$unitId/',
  path: '/kurs/$unitId/',
  getParentRoute: () => rootRouteImport,
} as any)
const KursUnitIdLessonIdRoute = KursUnitIdLessonIdRouteImport.update({
  id: '/kurs/$unitId/$lessonId',
  path: '/kurs/$unitId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const KursUnitIdCheckpointRoute = KursUnitIdCheckpointRouteImport.update({
  id: '/kurs/$unitId/checkpoint',
  path: '/kurs/$unitId/checkpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const KursUnitIdGuideRoute = KursUnitIdGuideRouteImport.update({
  id: '/kurs/$unitId/guide',
  path: '/kurs/$unitId/guide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ueben': typeof UebenRoute
  '/kurs/$unitId/$lessonId': typeof KursUnitIdLessonIdRoute
  '/kurs/$unitId/checkpoint': typeof KursUnitIdCheckpointRoute
  '/kurs/$unitId/guide': typeof KursUnitIdGuideRoute
  '/kurs/$unitId/': typeof KursUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ueben': typeof UebenRoute
  '/kurs/$unitId/$lessonId': typeof KursUnitIdLessonIdRoute
  '/kurs/$unitId/checkpoint': typeof KursUnitIdCheckpointRoute
  '/kurs/$unitId/guide': typeof KursUnitIdGuideRoute
  '/kurs/$unitId': typeof KursUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ueben': typeof UebenRoute
  '/kurs/$unitId/$lessonId': typeof KursUnitIdLessonIdRoute
  '/kurs/$unitId/checkpoint': typeof KursUnitIdCheckpointRoute
  '/kurs/$unitId/guide': typeof KursUnitIdGuideRoute
  '/kurs/$unitId/': typeof KursUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ueben'
    | '/kurs/$unitId/$lessonId'
    | '/kurs/$unitId/checkpoint'
    | '/kurs/$unitId/guide'
    | '/kurs/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ueben'
    | '/kurs/$unitId/$lessonId'
    | '/kurs/$unitId/checkpoint'
    | '/kurs/$unitId/guide'
    | '/kurs/$unitId'
  id:
    | '__root__'
    | '/'
    | '/ueben'
    | '/kurs/$unitId/$lessonId'
    | '/kurs/$unitId/checkpoint'
    | '/kurs/$unitId/guide'
    | '/kurs/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UebenRoute: typeof UebenRoute
  KursUnitIdLessonIdRoute: typeof KursUnitIdLessonIdRoute
  KursUnitIdCheckpointRoute: typeof KursUnitIdCheckpointRoute
  KursUnitIdGuideRoute: typeof KursUnitIdGuideRoute
  KursUnitIdIndexRoute: typeof KursUnitIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueben': {
      id: '/ueben'
      path: '/ueben'
      fullPath: '/ueben'
      preLoaderRoute: typeof UebenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs/$unitId/': {
      id: '/kurs/$unitId/'
      path: '/kurs/$unitId'
      fullPath: '/kurs/$unitId/'
      preLoaderRoute: typeof KursUnitIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs/$unitId/$lessonId': {
      id: '/kurs/$unitId/$lessonId'
      path: '/kurs/$unitId/$lessonId'
      fullPath: '/kurs/$unitId/$lessonId'
      preLoaderRoute: typeof KursUnitIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs/$unitId/checkpoint': {
      id: '/kurs/$unitId/checkpoint'
      path: '/kurs/$unitId/checkpoint'
      fullPath: '/kurs/$unitId/checkpoint'
      preLoaderRoute: typeof KursUnitIdCheckpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurs/$unitId/guide': {
      id: '/kurs/$unitId/guide'
      path: '/kurs/$unitId/guide'
      fullPath: '/kurs/$unitId/guide'
      preLoaderRoute: typeof KursUnitIdGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UebenRoute: UebenRoute,
  KursUnitIdLessonIdRoute: KursUnitIdLessonIdRoute,
  KursUnitIdCheckpointRoute: KursUnitIdCheckpointRoute,
  KursUnitIdGuideRoute: KursUnitIdGuideRoute,
  KursUnitIdIndexRoute: KursUnitIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
