// AUTO-GENERATED by scripts/generate-course-audio.ts — do not edit by hand.
// Maps a course sentence id to its normal and slow audio clips.
export const COURSE_AUDIO: Record<string, { src: string; slow: string }> = {
  "u01.l01.s01": { src: "/course/u01/audio/u01.l01.s01.mp3", slow: "/course/u01/audio/u01.l01.s01.slow.mp3" },
  "u01.l01.s02": { src: "/course/u01/audio/u01.l01.s02.mp3", slow: "/course/u01/audio/u01.l01.s02.slow.mp3" },
  "u01.l01.s03": { src: "/course/u01/audio/u01.l01.s03.mp3", slow: "/course/u01/audio/u01.l01.s03.slow.mp3" },
  "u01.l01.s04": { src: "/course/u01/audio/u01.l01.s04.mp3", slow: "/course/u01/audio/u01.l01.s04.slow.mp3" },
  "u01.l01.s05": { src: "/course/u01/audio/u01.l01.s05.mp3", slow: "/course/u01/audio/u01.l01.s05.slow.mp3" },
  "u01.l01.s06": { src: "/course/u01/audio/u01.l01.s06.mp3", slow: "/course/u01/audio/u01.l01.s06.slow.mp3" },
};
